=== pfeimich/config-generator/schemas/qwc-config-generator.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/qwc-services/qwc-config-generator/raw/master/schemas/qwc-config-generator.json",
  "title": "QWC Config generator",
  "type": "object",
  "properties": {
    "$schema": {
      "title": "JSON Schema",
      "description": "Reference to JSON schema of this config",
      "type": "string",
      "format": "uri",
      "default": "https://github.com/qwc-services/qwc-config-generator/raw/master/schemas/qwc-config-generator.json"
    },
    "service": {
      "title": "Service name",
      "type": "string",
      "const": "config-generator"
    },
    "themesConfig": {
      "title": "QWC2 themes configuration",
      "description": "Corresponds to contents of standalone QWC2 themesConfig.json",
      "type": "object",
      "properties": {
        "themes": {
          "type": "object"
        }
      },
      "required": [
        "themes"
      ]
    },
    "config": {
      "title": "Config options for Config generator",
      "type": "object",
      "properties": {
        "tenant": {
          "description": "Tenant name. Example: default",
          "type": "string"
        },
        "config_db_url": {
          "description": "Connection URL for configuration database. Example: postgresql:///?service=qwc_configdb",
          "type": "string",
          "format": "uri"
        },
        "default_qgis_server_url": {
          "description": "Default QGIS Server URL for OGC requests. Example: http://qwc-qgis-server/ows/",
          "type": "string",
          "format": "uri"
        },
        "qgis_projects_base_dir": {
          "description": "Base path for QGIS projects. Example: /data",
          "type": "string"
        },
        "qgis_projects_scan_base_dir": {
          "description": "Path for QGIS projects, which should be automatically detected. Must be a subdir qgis_projects_base_dir. Example: /data/scan",
          "type": "string"
        },
        "qgis_projects_gen_base_dir": {
          "description": "Path for generated QGIS projects, result of preprocessing. Must be a subdir of qgis_projects_base_dir. Can be the same as qgis_projects_scan_base_dir, in which case the theme autodetection will apply to generated QGIS projects. Example: /data/gen",
          "type": "string"
        },
        "permissions_default_allow": {
          "description": "Set whether resources are permitted or restricted by default. Example: true",
          "type": "boolean"
        },
        "validate_schema": {
          "description": "Validate configuration against schema. Example: true",
          "type": "boolean"
        },
        "config_path": {
          "description": "Target path for generated service configs and permissions, if not set by $OUTPUT_CONFIG_PATH. Example: /config-out",
          "type": "string"
        },
        "qwc2_base_dir": {
          "description": "Path to the QWC2 directory, which will be used to autodetect thumbnails. If qgis_projects_scan_base_dir is not set, then this option will be ignored. Example /qwc2",
          "type": "string"
        },
        "skip_print_layer_groups": {
          "description": "Skip group layers containing print layers",
          "type": "boolean"
        },
        "layer_opacities": {
          "description": "Layer opacity values for QGIS <= 3.10",
          "type": "object"
        },
        "split_categorized_layers": {
          "description": "Set to true to activate the categorize groups funcitonality",
          "type": "boolean"
        },
        "project_settings_read_timeout": {
          "description": "Timeout for GetProjectSettings request, default: 60sec",
          "type": "number"
        },
        "autogen_keyvaltable_datasets": {
          "description": "Whether to automatically generate data service datasets used for key-value relationships without requiring corresponding data resources to be created. Warning: this will expose the key and value fields of the key-value table as world readable. Default: false",
          "type": "boolean"
        }
      },
      "required": [
        "tenant",
        "default_qgis_server_url",
        "config_db_url",
        "qgis_projects_base_dir"
      ]
    },
    "services": {
      "title": "Service configs",
      "description": "Service specific config options for generating their service configs",
      "type": "array",
      "items": {
        "description": "Generator config for a service",
        "oneOf": [
          {"$ref": "#/definitions/common_service"},
          {"$ref": "#/definitions/mapViewer"},
          {"$ref": "#/definitions/ogc"}
        ]
      }
    }
  },
  "required": [
    "service",
    "themesConfig",
    "config",
    "services"
  ],
  "definitions": {
    "common_service": {
      "description": "Generator config for a QWC service",
      "type": "object",
      "properties": {
        "name": {
          "description": "Service name",
          "type": "string",
          "enum": [
            "adminGui",
            "data",
            "dbAuth",
            "elevation",
            "featureInfo",
            "mapinfo",
            "permalink",
            "print",
            "search",
            "legend"
          ]
        },
        "config": {
          "description": "QWC service config options (cf. its JSON schema). This is copied unmodified to the service config.",
          "type": "object"
        }
      },
      "required": [
        "name",
        "config"
      ]
    },
    "mapViewer": {
      "description": "Generator config for Map Viewer",
      "type": "object",
      "properties": {
        "name": {
          "description": "Service name",
          "type": "string",
          "const": "mapViewer"
        },
        "generator_config": {
          "description": "Additional config for generating MapViewer resources",
          "type": "object",
          "properties": {
            "qwc2_config": {
              "description": "Additional config for QWC2 application configuration",
              "type": "object",
              "properties": {
                "qwc2_config_file": {
                  "description": "Path to QWC2 config.json file. Example: /qwc2/config.json",
                  "type": "string"
                },
                "qwc2_index_file": {
                  "description": "Path to QWC2 index.html file. Example: /qwc2/index.html",
                  "type": "string"
                }
              },
              "required": [
                "qwc2_config_file",
                "qwc2_index_file"
              ]
            }
          },
          "required": [
            "qwc2_config"
          ]
        },
        "config": {
          "description": "Map Viewer config options (cf. JSON schema qwc-map-viewer.json). This is copied unmodified to the service config.",
          "type": "object"
        }
      },
      "required": [
        "name",
        "generator_config",
        "config"
      ]
    },
    "ogc": {
      "description": "Generator config for OGC service",
      "type": "object",
      "properties": {
        "name": {
          "description": "Service name",
          "type": "string",
          "const": "ogc"
        },
        "generator_config": {
          "description": "Additional config for generating OGC service resources",
          "type": "object",
          "properties": {
            "wms_services": {
              "description": "Additional config for WMS services",
              "type": "object",
              "properties": {
                "online_resources": {
                  "description": "Custom OnlineResources shown in GetCapabilities",
                  "type": "object",
                  "properties": {
                    "service": {
                      "description": "Default public base URL for OnlineResources",
                      "type": "string",
                      "format": "uri"
                    },
                    "feature_info": {
                      "description": "Public base URL for FeatureInfo OnlineResources",
                      "type": "string",
                      "format": "uri"
                    },
                    "legend": {
                      "description": "Public base URL for Legend OnlineResources",
                      "type": "string",
                      "format": "uri"
                    }
                  }
                }
              }
            }
          }
        },
        "config": {
          "description": "OGC service config options (cf. JSON schema qwc-ogc-service.json). This is copied unmodified to the service config.",
          "type": "object"
        }
      },
      "required": [
        "name",
        "config"
      ]
    }
  }
}

=== pfeimich/config-generator/tenantConfig.json
{
  "$schema": "https://github.com/qwc-services/qwc-config-generator/raw/master/schemas/qwc-config-generator.json",
  "service": "config-generator",
  "config": {
    "tenant": "default",
    "default_qgis_server_url": "http://localhost:8088/ows/",
    "config_db_url": "postgresql:///?service=qwc_configdb",
    "permissions_default_allow": true,
    "qgis_projects_base_dir": "../qwc-docker/volumes/qgs-resources",
    "qgis_projects_scan_base_dir": "../qwc-docker/volumes/qgs-resources/scan",
    "qgis_projects_gen_base_dir": "../qwc-docker/volumes/qgs-resources/gen",
    "qwc2_base_dir": "../qwc-docker/volumes/qwc2"
  },
  "themesConfig": {
    "defaultScales": [100000000, 50000000, 25000000, 10000000, 4000000, 2000000, 1000000, 400000, 200000, 80000, 40000, 20000, 10000, 8000, 6000, 4000, 2000, 1000, 500, 250, 100],
    "defaultPrintGrid": [{"s": 10000000, "x": 1000000, "y": 1000000}, {"s": 1000000, "x": 100000, "y": 100000}, {"s": 100000, "x": 10000, "y": 10000}, {"s": 10000, "x": 1000, "y": 1000}, {"s": 1000, "x": 100, "y": 100}, {"s": 100, "x": 10, "y": 10}],
    "defaultWMSVersion":"1.3.0",
    "defaultBackgroundLayers": [],
    "defaultSearchProviders": ["coordinates"],
    "defaultMapCrs": "EPSG:3857",
    "themes": {
      "items": [
        {
          "title": "Demo",
          "url": "/ows/qwc_demo",
          "default": true,
          "attribution": "Demo attribution",
          "attributionUrl": "https://127.0.0.1/",
          "backgroundLayers": [
            {
              "name": "bluemarble",
              "printLayer": "bluemarble_bg",
              "visibility": true
            },
            {
              "name": "mapnik",
              "printLayer": "osm_bg"
            }
          ],
          "searchProviders": [
            "coordinates",
            "nominatim",
            {
              "provider": "solr",
              "default": [
              ],
              "layers": {
                "countries": "ne_10m_admin_0_countries"
              }
            }
          ],
          "mapCrs": "EPSG:3857",
          "additionalMouseCrs": [],
          "extent": [-1000000, 4000000, 3000000, 8000000],
          "skipEmptyFeatureAttributes": true,
          "printResolutions": [300],
          "thumbnail": "default.jpg"
        },
	{
          "title": "Test WMS",
          "url": "/ows/scan/test",
          "backgroundLayers": [
            {
              "name": "hintergrundkarte_sw"
            }
          ]
        } 
      ],
      "backgroundLayers": [
        {
          "name": "mapnik",
          "title": "Open Street Map",
          "type": "osm",
          "source": "osm",
          "attribution": "OpenStreetMap contributors",
          "attributionUrl": "https://www.openstreetmap.org/copyright",
          "thumbnail": "img/mapthumbs/mapnik.jpg"
        },
        {
          "type": "wmts",
          "url": "http://gibs.earthdata.nasa.gov/wmts/epsg3857/best/BlueMarble_ShadedRelief/default/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.jpeg",
          "title": "Blue Marble",
          "name": "bluemarble",
          "tileMatrixPrefix": "",
          "tileMatrixSet": "GoogleMapsCompatible_Level8",
          "originX": -20037508.34278925,
          "originY": 20037508.34278925,
          "projection:": "EPSG:3857",
          "resolutions": [
            156543.03390625,
            78271.516953125,
            39135.7584765625,
            19567.87923828125,
            9783.939619140625,
            4891.9698095703125,
            2445.9849047851562,
            1222.9924523925781
          ],
          "tileSize": [
            256,
            256
          ],
          "thumbnail": "img/mapthumbs/default.jpg"
        },
	{
          "type": "wmts",
          "url": "https://geo.so.ch/api/wmts/1.0.0/ch.so.agi.hintergrundkarte_sw/default/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.png",
          "title": "Karte SW",
          "name": "hintergrundkarte_sw",
          "tileMatrixPrefix": "",
          "tileMatrixSet": "2056",
          "originX": 2420000,
          "originY": 1350000,
          "projection": "EPSG:2056",
          "resolutions": [
            4000,
            2000,
            1000,
            500,
            250,
            100,
            50,
            20,
            10,
            5,
            2.5,
            1,
            0.5,
            0.25,
            0.1
          ],
          "tileSize": [
            256,
            256
          ],
          "thumbnail": "img/mapthumbs/hintergrundkarte_sw.png"
        }
      ]
    }
  },
  "services": [
    {
      "name": "mapViewer",
      "generator_config": {
        "qwc2_config": {
          "qwc2_config_file": "../qwc-docker/volumes/config-in/default/config.json",
          "qwc2_index_file": "../qwc-docker/volumes/config-in/default/index.html"
        }
      },
      "config": {
        "qwc2_path": "~/development/config-generator/volumes/qwc2/",
        "auth_service_url": "/auth/",
        "data_service_url": "/api/v1/data/",
        "#document_service_url": "/api/v1/document/",
        "elevation_service_url": "/elevation/",
        "info_service_url": "/api/v1/featureinfo/",
        "legend_service_url": "/api/v1/legend/",
        "mapinfo_service_url": "/api/v1/mapinfo/",
        "ogc_service_url": "/ows/",
        "permalink_service_url": "/api/v1/permalink/",
        "#print_service_url": "/api/v1/print/",
        "search_service_url": "/api/v2/search/",
        "search_data_service_url": "/api/v2/search/geom/"
      }
    }
  ]
}
